### ISSUE TITLE
A bug that cause infinity waiting for the transaction checking...

### ISSUE THREAD

**Issue by wyf-ACCEPT** [Web3Camp-Labs/hardhat-metamask-connector#1]
https://github.com/Web3Camp-Labs/hardhat-metamask-connector/blob/066e4e02d00a15beec3871866e12e96cfa0c5f95/src/index.ts#L56

It should be rewrited as:
`this.transactions.set(req.body.id, req.body.hash);`

But not:
`this.transactions.set(req.body.txId, req.body.txHash);`

Otherwise, the variable `this.transactions` will add a `undefined => undefined` key-value pair, and thus the line 
https://github.com/Web3Camp-Labs/hardhat-metamask-connector/blob/066e4e02d00a15beec3871866e12e96cfa0c5f95/src/index.ts#L88
will always return, and the user will see the info "Checking for transaction: ..." repeated forever.

**Comment by xrdavies** [comment]
@wyf-ACCEPT  Thank you so much! Already fixed, and it will be published in version 1.1.3
